version: "2"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /home/pi5/Documents/Config:/config
      - /home/pi5/Documents/TV:/tv
      - /home/pi5/Documents/Movies:/movies
    restart: unless-stopped