version: "2"
services:
  plex:
	image: ghcr.io/linuxserver/plex
	container_name: plex
	network_mode: host
	environment:
	  - PUID=1000
	  - PGID=1000
	  - VERSION=docker
	volumes:
	  - /home/pi4/Documents/Config:/config
	  - /home/pi4/Documents/TV:/tv
	  - /home/pi4/Documents/Movies:/movies
	restart: unless-stopped