version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_files:/files
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=something
      - GENERIC_TIMEZONE=Asia/Kolkata
      - TZ=Asia/Kolkata
      
      # Critical environment variables for Cloudflare Tunnel
      - N8N_HOST=n8n.pageinnovator.in
      - WEBHOOK_URL=https://n8n.pageinnovator.in/
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - N8N_EDITOR_BASE_URL=https://n8n.pageinnovator.in
      - N8N_CORS_ORIGIN=https://n8n.pageinnovator.in
      - N8N_WEBSOCKET=true
      
      # Database configuration (keep your existing values)
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n-db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=
    depends_on:
      n8n-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - n8n_network

  n8n-db:
    image: postgres:13-alpine
    container_name: n8n-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=
      - TZ=Asia/Kolkata
    volumes:
      - n8n_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U n8n -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - n8n_network

volumes:
  n8n_data:
    driver: local
  n8n_db_data:
    driver: local
  n8n_files:
    driver: local

networks:
  n8n_network:
    driver: bridge
