version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin_server
    restart: unless-stopped
    ports:
      - 8096:8096  # Web interface
      - 8920:8920  # HTTPS (optional)
    environment:
      - TZ=Asia/Kolkata  # Set your timezone
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /mnt/nas/data/admin/files/Movies:/media/movies:rw  # All media in Movies folder
    networks:
      - media_network

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=Asia/Kolkata
    volumes:
      - radarr_config:/config
      - /mnt/nas/data/admin/files/Movies:/movies  # All media goes here
    networks:
      - media_network
    depends_on:
      - qbittorrent

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=Asia/Kolkata
    volumes:
      - sonarr_config:/config
      - /mnt/nas/data/admin/files/Movies:/movies  # All media goes here
    networks:
      - media_network
    depends_on:
      - qbittorrent

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=Asia/Kolkata
    volumes:
      - jackett_config:/config
    networks:
      - media_network

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - 8081:8080  # Changed from 8080 to avoid Nextcloud conflict
      - 6881:6881
      - 6881:6881/udp
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8081
    volumes:
      - qbittorrent_config:/config
      - /mnt/nas/data/admin/files/Movies:/movies  # All downloads go here
    networks:
      - media_network

networks:
  media_network:
    driver: bridge

volumes:
  jellyfin_config:
  jellyfin_cache:
  radarr_config:
  sonarr_config:
  jackett_config:
  qbittorrent_config:
