version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin_server
    restart: unless-stopped
    ports:
      - 8096:8096  # Web interface
      - 8920:8920  # HTTPS (optional)
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /mnt/nas/data/admin/files/Movies:/media/movies:rw  # All media in Movies folder
    networks:
      - media_network

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=Asia/Kolkata
    volumes:
      - radarr_config:/config
      - /mnt/nas/data/admin/files/Movies:/movies  # Movies folder
    networks:
      - media_network
    depends_on:
      - transmission

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=Asia/Kolkata
    volumes:
      - sonarr_config:/config
      - /mnt/nas/data/admin/files/Movies:/movies  # Movies folder
    networks:
      - media_network
    depends_on:
      - transmission

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=Asia/Kolkata
    volumes:
      - jackett_config:/config
      - /mnt/nas/data/admin/files/Jackett:/downloads  # Store indexer results
    networks:
      - media_network

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    ports:
      - 9091:9091  # Web UI
      - 51413:51413  # Torrent TCP
      - 51413:51413/udp  # Torrent UDP
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=Asia/Kolkata
      - USER=admin
      - PASS=lucifer
    volumes:
      - /mnt/nas/qbittorrent/config:/config
      - /mnt/nas/data/admin/files/Movies:/downloads  # Movies folder
    networks:
      - media_network

networks:
  media_network:
    driver: bridge

volumes:
  jellyfin_config:
  jellyfin_cache:
  radarr_config:
  sonarr_config:
  jackett_config:
  qbittorrent_config:
